### ISSUE TITLE
hook failed with auth & sync

### ISSUE THREAD

**Issue by dpoellath** [feathersjs/authentication#540]
get error in hook updateEntity from file update-entity.js on patched event (on user model), because hook (2nd argument) is not delivered over sync

```

TypeError: Cannot read property 'app' of undefined
    at Object.updateEntity (/Users/user/server/node_modules/feathers-authentication/lib/socket/update-entity.js:5:17)
    at emitOne (events.js:101:20)
    at Object.emit [as _emit] (events.js:188:7)
    at /Users/user/server/node_modules/feathers-sync/src/amqp.js:99:27
    at /Users/user/server/node_modules/feathers-sync/src/amqp.js:13:7
    at Array.forEach (native)
    at onmessage (/Users/user/server/node_modules/feathers-sync/src/amqp.js:12:24)
    at channel.consume.noAck (/Users/user/server/node_modules/feathers-sync/src/amqp.js:36:13)
    at Channel.BaseChannel.dispatchMessage (/Users/user/server/node_modules/amqplib/lib/channel.js:466:12)
    at Channel.BaseChannel.handleDelivery (/Users/user/server/node_modules/amqplib/lib/channel.js:475:15)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at /Users/user/server/node_modules/amqplib/lib/channel.js:263:10
    at Channel.content [as handleMessage] (/Users/user/server/node_modules/amqplib/lib/channel.js:316:9)
    at Channel.C.acceptMessageFrame (/Users/user/server/node_modules/amqplib/lib/channel.js:231:31)
    at Channel.C.accept (/Users/user/server/node_modules/amqplib/lib/channel.js:384:17)
    at Connection.mainAccept [as accept] (/Users/user/server/node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/Users/user/server/node_modules/amqplib/lib/connection.js:476:48)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by dpoellath** [comment]
update: could be fixed, if you write a wrapper for the hook, because you have the app object in the setup call, when you init the event listener (handler.js)

**Comment by marshallswain** [comment]
Thanks @dpoellath for figuring this out.

**Comment by daffl** [comment]
Related: https://github.com/feathersjs/feathers-sync/issues/32

I will definitely give `feathers-sync` some more love with the [next version](https://blog.feathersjs.com/after-auk-whats-next-for-feathers-buzzard-c68358a3e62f).

@marshallswain from what I understand I think the fix @dpoellath suggested would still be worth implementing.

**Comment by ekryski** [comment]
Is this still an issue? Seems to be fixed here but there is still some outstanding work to be done to address https://github.com/feathersjs/feathers-sync/issues/32?
