### ISSUE TITLE
Requires Path Option

### ISSUE THREAD

**Issue by flyboarder** [feathersjs/authentication#608]
### Steps to reproduce

remove "path" from auth options

### Expected behavior
Should use default "/authentication" path

### Actual behavior
Getting error
```
Node.js Error...
/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/node_modules/feathers-commons/lib/utils.js:33
  return name.replace(/^(\/*)|(\/*)$/g, '');
             ^

TypeError: Cannot read property 'replace' of undefined
    at stripSlashes (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/node_modules/feathers-commons/lib/utils.js:33:14)
    at EventEmitter.service (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/node_modules/feathers/lib/application.js:56:50)
    at Function.feathers.core.service.cljs$core$IFn$_invoke$arity$2 (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/nodejs.out/feathers/core.js:95:12)
    at feathers$core$service (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/nodejs.out/feathers/core.js:81:30)
    at feathers$authentication$service (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/nodejs.out/feathers/authentication.js:21:33)
    at feathers$app$authentication (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/nodejs.out/feathers/app.js:39:40)
    at Object.<anonymous> (/Users/matt/.boot/cache/tmp/Users/matt/Projects/cannabit/cannabit-community/imw/-u910tu/nodejs.out/meta/server.js:8:29)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

```

### System configuration

**Module versions** 
"latest" in package.json

**NodeJS version**:
9

**Operating System**:
macOS 10.12

**Comment by daffl** [comment]
Feathers v4 authentication requires you to register the service on the path you want explicitly and no longer has a path option.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
