### ISSUE TITLE
TypeError: Cannot read property '_strategy' of undefined

### ISSUE THREAD

**Issue by joodroid** [feathersjs/authentication#632]
### Steps to reproduce

- [ ] Tell us what broke. The more detailed the better.

error:  TypeError: Cannot read property '_strategy' of undefined
    at Object.<anonymous> (/Users/rizkyaisis/Documents/GitFile/aspirasi-services/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:40:23)
    at promise.then.hookObject (/Users/rizkyaisis/Documents/GitFile/aspirasi-services/node_modules/@feathersjs/commons/lib/hooks.js:174:73)
    at <anonymous>
error:  TypeError: Cannot read property '_strategy' of undefined
    at Object.<anonymous> (/Users/rizkyaisis/Documents/GitFile/aspirasi-services/node_modules/@feathersjs/authentication/lib/hooks/authenticate.js:40:23)
    at promise.then.hookObject (/Users/rizkyaisis/Documents/GitFile/aspirasi-services/node_modules/@feathersjs/commons/lib/hooks.js:174:73)
    at <anonymous>

- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior

Succesful authentication

### Actual behavior

 Register and Login won't run / nothing happen after button clicked

### System configuration

Run Android Studio, React Native, Feathers JS

Tell us about the applicable parts of your setup.

**React Native Version**:
 react-native : version 0.5.2

**Module Loader**:

**Comment by daffl** [comment]
Did you configure `@feathersjs/authentication` properly?

**Comment by joodroid** [comment]
Thank you daffl,

I've figured the case on [https://docs.feathersjs.com/api/authentication/server.html](url)
